# Generated by Django 5.1.6 on 2025-02-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
